<!-- begin content -->
<div class="row app-container">
    <div class="row">
        <div class="column">
            <a class="button button-primary" href="/new">Back</a>
        </div>
    </div>
    <div class="row">
        <div class="column">
            <h1>Create New</h1>
            <form method="post" action="/new/create">
                <div class="row">
                    <div class="six columns">
                        <label for="txtTitle">Title</label>
                        <input class="u-full-width" type="text" placeholder="Some Title" id="txtTitle" name="txtTitle">
                    </div>
                    <div class="six columns">
                        <label for="txtDate">Date</label>
                        <input class="u-full-width" type="date" placeholder="Date" id="txtDate" name="txtDate">
                    </div>
                </div>
                <div class="row">
                    <div class="six columns">
                        <label for="cboStatus">Status</label>
                        <select class="u-full-width" id="cboStatus" name="cboStatus">
                            <option value="public">Public</option>
                            <option value="private">Private</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="column">
                        <label for="txtDescription">Description</label>
                        <textarea class="u-full-width" placeholder="Description..." id="txtDescription" name="txtDescription"></textarea>
                    </div>
                </div>
                <input class="button-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>
</div>
<!-- end content -->