<?php
use Underscore\Underscore as _;

?>
<div class="row app-bar">
    <div class="column">
        <a href="/" class="option">Home</a>
        <?php
        _::each(app_configs::getNamespaces(), function($namespace){
            ?>
            <a href="/<?= $namespace ?>" class="option">
                <?= $namespace ?>
            </a>    
            <?php
        });
        ?>
    </div>
</div>